Add Cucumber tests
France-ioi/CodecastTaskBackend pull request #8
Opened 2023-03-27 16:15 UTC by SebastienTainon

- Add Cucumber.js BDD test framework
- Add hooks for tests (db setup, server setup)
- Add tests for endpoint /tasks/{taskId}
- Add CircleCI config

2023-03-28 08:08 UTC, smadbe requested changes

2023-03-28 08:08 UTC, smadbe commented on features/steps/task_steps.ts
> +    const taskId = getRandomId();
It is usually better not to rely on any randomness in tests (or a least to mock the random function to have a fixed value)

2023-03-29 12:50 UTC, SebastienTainon commented on features/get_task.feature
> +    Then the server response should include the following object: "get_task_response.json"
I've changed to a static Gherkin datatable, it's indeed more readable, thanks! :+1:

2023-03-29 13:20 UTC, smadbe approved these changes
👍

2023-03-29 13:20 UTC, smadbe commented on features/steps/task_steps.ts
> +    console.log(payload);
debugging leftover?

2023-03-29 13:28 UTC, merged